### PR TITLE
WIP Add eval command

### LINKED ISSUE #64: support redis eval script (lua)
Can we do support the EVAL command?

https://redis.io/commands/eval

### PR DESCRIPTION
**Pull request by Negashev**
close #64
Work with simple call

```bash
> eval "return redis.call('set','foo','bar')" 0
OK
> GET foo
"bar"
> eval "return redis.call('GET','foo')" 0
bar
> eval "return 10" 0
(integer) 10
> eval "return {1,2,3.3333,'foo',nil,'bar'}" 0 <--- some problems (redis return only 4 keys)
1) (integer) 1
2) (integer) 2
3) (integer) 3
4) "foo"
5) "bar"
> eval "return {1,2,{3,'Hello World!'}}" 0
1) (integer) 1
2) (integer) 2
3) 1) (integer) 3
   2) "Hello World!"
> eval "return redis.call(KEYS[1],KEYS[2], 134)" 2 set foo
OK
> GET foo
134
> eval "return {KEYS[1],KEYS[2],ARGV[1],ARGV[2]}" 2 key1 key2 first second
1) key1
2) key2
3) first
4) second

```

Ready

- [x] `redis.call` from the box
- [x] `KEYS` and `ARGV` in lua
- [ ] connect to tidis internal without golang redis client

### CODE REVIEW

**Comment by anhldbk** [comment]
@Negashev @1995parham PTAL

**Comment by yongman** [comment]
This repo will be archived, cause an alternative `Tidis` will be opensource developed by PingCAP official which already support EVAL/EVALSHA commands. It will open in a few days, please pay attention. :-)

**Comment by anhldbk** [comment]
@yongman Thank you for this incredible work!

**Comment by yongman** [comment]
@Negashev @anhldbk Please refer to https://github.com/tidb-incubator/tidis

**Pull request closed without merging**
