### PR TITLE
Handle nil object in sadd

### LINKED ISSUE #88: Panic when SAdd on priviously Set key.
I created a normal key by `Set` and then `SAdd` on it, this cause nil reference panic which I think was caused by returning nil and no error 

https://github.com/yongman/tidis/blob/8da5613fe14cd93d4d16ccd8d522747c943c969c/tidis/t_set.go#L48

which cause panic on the following

https://github.com/yongman/tidis/blob/8da5613fe14cd93d4d16ccd8d522747c943c969c/tidis/t_set.go#L100

if you agree I can create a PR for this by checking the return value besides error.

### PR DESCRIPTION
**Pull request by 1995parham**
closes  #88

### CODE REVIEW

**Comment by yongman** [comment]
@1995parham you can review the code and update your merge request if you agree. :-)

**Comment by 1995parham** [comment]
Thanks for the review, I will update it.

**Comment by 1995parham** [comment]
I just want to remind that I am available if this PR will need more change.

**Comment by yongman** [comment]
@1995parham thanks for your work.

**Pull request merged**
