### PR TITLE
add zrank/zrevrank command, and test ok.

### PR DESCRIPTION
**Pull request by aronfan**
add zrank/zrevrank, these are very import for game dev.

### CODE REVIEW

**Comment by yongman** [comment]
It will be better to add test cases to unit test to the new commands.

**Comment by yongman** [comment]
@aronfan Could you add unit tests to tests/test_zset.py  together with the code commit ?

**Comment by aronfan** [comment]
I don't know and use python... All my unit test or stress test are written by Go

**Comment by aronfan** [comment]
The "zrevrank" will have a better impl by pingcap to impl the reverse iteration in snapshot.

**Comment by yongman** [comment]
@aronfan the reverse iteration in snapshot seems did not implemented a few month ago.

**Comment by aronfan** [comment]
I contact the engineers of pingcap on wechat, and add a issue: https://github.com/pingcap/tidb/issues/8901

**Comment by yongman** [comment]
@aronfan I will merge this pull request, I will add unit tests to these commands later. 
And commands need be optimized after reverse iteration implemented.

Thanks for your work.

**Pull request merged**
